#python -m fastai2.launch config/train_rn18_all.py  --do_pred 1
#python -m fastai2.launch config/train_rn18_nofr.py  --do_pred 1
#python -m fastai2.launch config/train_rn18.py  --do_pred 1
#python -m fastai2.launch config/train_rn34_nofr.py  --do_pred 1
#python -m fastai2.launch config/train_rn34.py  --do_pred 1
python -m fastai2.launch config/train_rn50_all.py  --do_pred 1
python -m fastai2.launch config/train_rn50_nofr.py  --do_pred 1
python -m fastai2.launch config/train_xrn18d_nofr.py  --do_pred 1
python -m fastai2.launch config/train_xrn18dr_nofr.py  --do_pred 1
python -m fastai2.launch config/train_xrn18_nofr.py  --do_pred 1
python -m fastai2.launch config/train_xrn18.py  --do_pred 1
python -m fastai2.launch config/train_xrn34d_nofr.py  --do_pred 1
python -m fastai2.launch config/train_xrn34dr_nofr.py  --do_pred 1
python -m fastai2.launch config/train_xrn34_nofr.py  --do_pred 1
python -m fastai2.launch config/train_xrn50_all.py  --do_pred 1
python -m fastai2.launch config/train_xrn50d_nofr.py  --do_pred 1
python -m fastai2.launch config/train_xrn50d.py  --do_pred 1
python -m fastai2.launch config/train_xrn50dr_nofr.py  --do_pred 1
python -m fastai2.launch config/train_xrn50dr.py  --do_pred 1
python -m fastai2.launch config/train_xrn50_nofr.py  --do_pred 1
