#AUTOGENERATED! DO NOT EDIT! File to edit: dev/03_train3d_scratch_extract_features.ipynb (unless otherwise specified).

__all__ = ['get_3d_dsets']

#Cell
from .imports import *
from .metadata import *
from .preprocess import *
from .train import *
from .train3d import *

#Cell
def get_3d_dsets(df, path=path_jpg256):
    df_series = df.reset_index().set_index('SeriesInstanceUID').sort_values("ImagePositionPatient2")
    rct = ReadCT(df_series, path)
    sids = df_series.index.unique()[:100]
    splits = RandomSplitter(valid_pct=0.1, seed=42)(sids)
    dsets = Datasets(sids, [[rct.x],[rct.y]], splits=splits)
    return dsets